#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jul 13 13:48:47 2010

import wx
import MySQLdb
# begin wxGlade: extracode
# end wxGlade

Movis = [] 

class Bajasdepely(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Bajasdepely.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.db = MySQLdb.connect('localhost', 'cintia', 'cintia', 'cintia', charset='UTF8')
        self.panel_1 = wx.Panel(self, -1)
        self.sizer_2_staticbox = wx.StaticBox(self.panel_1, -1, "Bajas de Peliculas")
        self.nom_pely = wx.StaticText(self.panel_1, -1, "Nombre de la pelicula :")
        self.text_nombre = wx.TextCtrl(self.panel_1, -1, "")
        self.static_line_1 = wx.StaticLine(self.panel_1, -1)
        self.static_line_2 = wx.StaticLine(self.panel_1, -1)
        self.Cancelar_ = wx.Button(self.panel_1, -1, "Cancelar")
        self.Aceptar_ = wx.Button(self.panel_1, -1, "Aceptar")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnCancelar, self.Cancelar_)
        self.Bind(wx.EVT_BUTTON, self.OnAceptar, self.Aceptar_)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Bajasdepely.__set_properties
        self.SetTitle("Eliminar")
        self.text_nombre.SetMinSize((160, 27))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Bajasdepely.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(self.nom_pely, 0, 0, 0)
        grid_sizer_1.Add(self.text_nombre, 0, 0, 0)
        grid_sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.static_line_2, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.Cancelar_, 0, 0, 0)
        grid_sizer_1.Add(self.Aceptar_, 0, wx.ALIGN_RIGHT, 0)
        sizer_3.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnCancelar(self, event): # wxGlade: Bajasdepely.<event_handler>
        self.Close()

    def OnAceptar(self, event): # wxGlade: Bajasdepely.<event_handler>
        clientes = self.text_nombre.GetValue()
        c = self.db.cursor()
        c.execute ('''SELECT id_film ,Pelicula , Genero FROM Videoclub WHERE  Pelicula =%s''',(clientes))
        q = c.fetchall()
        for cosa in q:
            Movis.append(str(cosa[0]) + '-' +cosa[1] + '-' +cosa[2])
        print Movis
        for todo in Movis :
            a = todo.strip()  
            cosa = a.split('-')
            print cosa
            cine = str(cosa[0])
            
        dlg = wx.SingleChoiceDialog(None, 'Los Peliculas que cumplen con su criterio son:','eliminar la pelicula',Movis, wx.CHOICEDLG_STYLE) 
        
        if dlg.ShowModal() == wx.ID_OK:
            print 'You selected: %s\n' % dlg.GetStringSelection()
            c.execute('''DELETE from Videoclub WHERE id_film = %s''' , (cine))
            wx.MessageBox(u'La pelicula se ha eliminado correctamente', 'Ok', wx.OK | wx.ICON_EXCLAMATION, None)
        
        c.close()
        self.Close()
# end of class Bajasdepely


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Bajas = Bajasdepely(None, -1, "")
    app.SetTopWindow(Bajas)
    Bajas.Show()
    app.MainLoop()
