#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jul  6 13:20:02 2010

import wx
import MySQLdb
# begin wxGlade: extracode
# end wxGlade



class Modificar(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Modificar.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        self.db = MySQLdb.connect('localhost', 'cintia', 'cintia', 'cintia', charset='UTF8')
        wx.Frame.__init__(self, *args, **kwds)
        self.frase = wx.StaticText(self, -1, "Ingrese la Peli a Modificar ")
        self.static_line_1 = wx.StaticLine(self, -1)
        self.peliculas = wx.StaticText(self, -1, "Pelicula :")
        self.text_peli = wx.TextCtrl(self, -1, "")
        self.Cancelar_ = wx.Button(self, -1, "Cancelar")
        self.Aceptar_ = wx.Button(self, -1, "Aceptar")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnCancelar, self.Cancelar_)
        self.Bind(wx.EVT_BUTTON, self.OnAceptar, self.Aceptar_)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Modificar.__set_properties
        self.SetTitle("PeliaModificar")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("/home/tt06/videoclub/logodevideo.jpeg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.text_peli.SetMinSize((160, 27))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Modificar.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(5, 2, 0, 0)
        grid_sizer_1.Add(self.frase, 0, wx.EXPAND, 5)
        grid_sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.peliculas, 0, 0, 0)
        grid_sizer_1.Add(self.text_peli, 0, 0, 0)
        grid_sizer_1.Add(self.Cancelar_, 0, wx.EXPAND|wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.Aceptar_, 0, wx.EXPAND|wx.ALIGN_RIGHT, 0)
        sizer_4.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

    def OnCancelar(self, event): # wxGlade: Modificar.<event_handler>
        print "Event handler `OnCancelar' not implemented!"
        event.Skip()

    def OnAceptar(self, event): # wxGlade: Modificar.<event_handler>
        pelicula = self.text_peli.GetValue()
        self.text_peli.SetValue('')
        c.self.db.cursor()
        c.execute('''UPDATE VideoClub set id_film,pelicula,genero FROM Videoclub WHERE peliculas = %s ''',(pelicula))
        c.close()
            
        
            

# end of class Modificar


if __name__ == "__main__":
    modpeli = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Modificarsocio = Modificar(None, -1, "")
    modpeli.SetTopWindow(Modificarsocio)
    Modificarsocio.Show()
    modpeli.MainLoop()
