#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jun 22 14:21:44 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class Prestamos(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Prestamos.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.retiro_ = wx.StaticText(self, -1, "Dia Retiro : ")
        self.date_retiro = wx.DatePickerCtrl(self, -1)
        self.label_reitegro = wx.StaticText(self, -1, "Reitegro : ")
        self.date_reitegro = wx.DatePickerCtrl(self, -1)
        self.Aceptar_ = wx.Button(self, -1, "Aceptar")
        self.button_1 = wx.Button(self, -1, "Cancelar ")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnAceptar, self.Aceptar_)
        self.Bind(wx.EVT_BUTTON, self.OnCancelar, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Prestamos.__set_properties
        self.SetTitle("Prestamos")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Prestamos.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(self.retiro_, 0, 0, 0)
        grid_sizer_1.Add(self.date_retiro, 0, 0, 0)
        grid_sizer_1.Add(self.label_reitegro, 0, 0, 0)
        grid_sizer_1.Add(self.date_reitegro, 0, 0, 0)
        grid_sizer_1.Add(self.Aceptar_, 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnAceptar(self, event): # wxGlade: Prestamos.<event_handler>
        print "Event handler `OnAceptar' not implemented!"
        event.Skip()

    def OnCancelar(self, event): # wxGlade: Prestamos.<event_handler>
        print "Event handler `OnCancelar' not implemented!"
        event.Skip()

# end of class Prestamos


class Prestamos(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        prestamos  = (None, -1, "")
        self.SetTopWindow(prestamos )
        prestamos .Show()
        return 1

# end of class Prestamos

if __name__ == "__main__":
    app = Prestamos(0)
    app.MainLoop()
