#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Jun 23 13:55:04 2010

import wx
import MySQLdb
# begin wxGlade: extracode
# end wxGlade

peli = []
clientes = []

class Prestamos(wx.Frame):
    def __init__(self, *args, **kwds):
        self.db = MySQLdb.connect('localhost', 'cintia', 'cintia', 'cintia', charset='UTF8')
        c = self.db.cursor()
        c.execute('''select * from Videoclub''')
        q = c.fetchall()
        for Videoclub in q :
            peli.append(Videoclub[1])
        
        c.execute('''select * from Socios''') 
        q = c.fetchall()
        for Socios in q :
            clientes.append(Socios[1]) 
            
        c.close()  
            
        # begin wxGlade: Prestamos.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.socio_ = wx.StaticText(self.panel_1, -1, "Socios : ")
        self.text_socios = wx.TextCtrl(self.panel_1, -1, "")
        self.pelicula_ = wx.StaticText(self.panel_1, -1, "Pelicula : ")
        self.combo_peli = wx.ComboBox(self.panel_1, -1, choices=["Terror ", "Romantica", "Drama", "Ficcion", "Infantil", "Comedia"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.label_retiro = wx.StaticText(self.panel_1, -1, "Dia retiro :")
        self.fecha_retiro = wx.DatePickerCtrl(self.panel_1, -1)
        self.reitegro_ = wx.StaticText(self.panel_1, -1, "Dia reitegro:")
        self.fecha_reitegro = wx.DatePickerCtrl(self.panel_1, -1)
        self.ingresar_ = wx.Button(self.panel_1, -1, "Ingresar")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnIngresar, self.ingresar_)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Prestamos.__set_properties
        self.SetTitle("Prestamos")
        self.text_socios.SetMinSize((120, 27))
        self.combo_peli.SetSelection(-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Prestamos.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(7, 2, 0, 0)
        grid_sizer_1.Add(self.socio_, 0, 0, 0)
        grid_sizer_1.Add(self.text_socios, 0, 0, 0)
        grid_sizer_1.Add(self.pelicula_, 0, 0, 0)
        grid_sizer_1.Add(self.combo_peli, 0, 0, 0)
        grid_sizer_1.Add(self.label_retiro, 0, 0, 0)
        grid_sizer_1.Add(self.fecha_retiro, 0, 0, 0)
        grid_sizer_1.Add(self.reitegro_, 0, 0, 0)
        grid_sizer_1.Add(self.fecha_reitegro, 0, 0, 0)
        grid_sizer_1.Add(self.ingresar_, 0, 0, 0)
        self.panel_1.SetSizer(grid_sizer_1)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnIngresar(self, event): # wxGlade: Prestamos.<event_handler>
       self.Close()
# end of class Prestamos


class App(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        PrestFrame = Prestamos(None, -1, "")
        self.SetTopWindow(PrestFrame)
        PrestFrame.Show()
        return 1

# end of class App

if __name__ == "__main__":
    Prest = App(0)
    Prest.MainLoop()
