#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Jul  5 13:21:42 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MyRegistro(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyRegistro.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        
        # Menu Bar
        self.menu_re = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "A&ltadePeliculas", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "A&ltadeSocios", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "A&ltadeAlquiler", "", wx.ITEM_NORMAL)
        self.menu_re.Append(wxglade_tmp_menu, "A&lta")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "M&odificarPelicula", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "M&odificarSocios", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "M&odificarAlquiler", "", wx.ITEM_NORMAL)
        self.menu_re.Append(wxglade_tmp_menu, "M&odificar")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "B&ajasPelicula", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "B&ajasSocios", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "B&ajasAlquiler", "", wx.ITEM_NORMAL)
        self.menu_re.Append(wxglade_tmp_menu, "B&ajas")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "L&istadodePeliculas", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "L&istadodeSocios", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "L&IistadodeAlquiler", "", wx.ITEM_NORMAL)
        self.menu_re.Append(wxglade_tmp_menu, "L&istado")
        wxglade_tmp_menu = wx.Menu()
        self.menu_re.Append(wxglade_tmp_menu, "")
        self.SetMenuBar(self.menu_re)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnAltapeli, id=-1)
        self.Bind(wx.EVT_MENU, self.OnAltasocio, id=-1)
        self.Bind(wx.EVT_MENU, self.OnAltaalquiler, id=-1)
        self.Bind(wx.EVT_MENU, self.OnModipelic, id=-1)
        self.Bind(wx.EVT_MENU, self.OnModisocios, id=-1)
        self.Bind(wx.EVT_MENU, self.OnModialquiler, id=-1)
        self.Bind(wx.EVT_MENU, self.OnBajapeli, id=-1)
        self.Bind(wx.EVT_MENU, self.OnBajassocios, id=-1)
        self.Bind(wx.EVT_MENU, self.OnBajasalquiler, id=-1)
        self.Bind(wx.EVT_MENU, self.OnListapeli, id=-1)
        self.Bind(wx.EVT_MENU, self.OnListasocios, id=-1)
        self.Bind(wx.EVT_MENU, self.OnListaalquiler, id=-1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyRegistro.__set_properties
        self.SetTitle("VideoClubRita")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyRegistro.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnAltapeli(self, event): # wxGlade: MyRegistro.<event_handler>
        pass

    def OnAltasocio(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnAltasocio' not implemented!"
        event.Skip()

    def OnAltaalquiler(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnAltaalquiler' not implemented!"
        event.Skip()

    def OnModipelic(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnModipelic' not implemented!"
        event.Skip()

    def OnModisocios(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnModisocios' not implemented!"
        event.Skip()

    def OnModialquiler(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnModialquiler' not implemented!"
        event.Skip()

    def OnBajapeli(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnBajapeli' not implemented!"
        event.Skip()

    def OnBajassocios(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnBajassocios' not implemented!"
        event.Skip()

    def OnBajasalquiler(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnBajasalquiler' not implemented!"
        event.Skip()

    def OnListapeli(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnListapeli' not implemented!"
        event.Skip()

    def OnListasocios(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnListasocios' not implemented!"
        event.Skip()

    def OnListaalquiler(self, event): # wxGlade: MyRegistro.<event_handler>
        print "Event handler `OnListaalquiler' not implemented!"
        event.Skip()

# end of class MyRegistro


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    re_ = MyRegistro(None, -1, "")
    app.SetTopWindow(re_)
    re_.Show()
    app.MainLoop()
