#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jul 13 15:18:26 2010

import wx
import MySQLdb
# begin wxGlade: extracode
# end wxGlade
Socios =[]


class Bajasdesocios(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Bajasdesocios.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.db = MySQLdb.connect('localhost', 'cintia', 'cintia', 'cintia', charset='UTF8')
        self.panel_1 = wx.Panel(self, -1)
        self.sizer_2_staticbox = wx.StaticBox(self.panel_1, -1, "Bajas de Socios")
        self.socio_ = wx.StaticText(self.panel_1, -1, "Nombre del Socio :")
        self.text_socio = wx.TextCtrl(self.panel_1, -1, "")
        self.static_line_1 = wx.StaticLine(self.panel_1, -1)
        self.static_line_2 = wx.StaticLine(self.panel_1, -1)
        self.Cancelar = wx.Button(self.panel_1, -1, "Cancelar")
        self.Aceptar = wx.Button(self.panel_1, -1, "Aceptar")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnCancelar, self.Cancelar)
        self.Bind(wx.EVT_BUTTON, self.OnAceptar, self.Aceptar)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Bajasdesocios.__set_properties
        self.text_socio.SetMinSize((160, 27))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Bajasdesocios.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_1.Add(self.socio_, 0, 0, 0)
        grid_sizer_1.Add(self.text_socio, 0, 0, 0)
        grid_sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.Cancelar, 0, 0, 0)
        grid_sizer_2.Add(self.Aceptar, 0, wx.ALIGN_RIGHT, 0)
        sizer_2.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnCancelar(self, event): # wxGlade: Bajasdesocios.<event_handler>
        self.Close()

    def OnAceptar(self, event): # wxGlade: Bajasdesocios.<event_handler>
        asociados = self.text_socio.GetValue()
        
        c = self.db.cursor()
        c.execute ('''SELECT  id_socios,Apellido,Nombres FROM Socios  WHERE  Apellido = %s ''',(asociados))
        q = c.fetchall()
        for baja in q :
            Socios.append(str(baja[0])+  '-' + baja[1] + '-' + baja[2])
            print Socios
        for todo in Socios :
            a = todo.strip() 
            baja = a.split('-')
            print baja 
            algo = str(baja[0])
            
        dlg = wx.SingleChoiceDialog(None, 'Los Socios que cumplen con su criterio son:','eliminar socios',Socios , wx.CHOICEDLG_STYLE) 
            
            
        if dlg.ShowModal() == wx.ID_OK:
            print 'You selected: %s\n' % dlg.GetStringSelection()
            
            c.execute('''DELETE from Socios WHERE id_socios = %s''' , (algo))
            wx.MessageBox(u'La pelicula se ha eliminado correctamente', 'Ok', wx.OK | wx.ICON_EXCLAMATION, None)
        
        c.close()
        self.Close()
    
        

# end of class Bajasdesocios


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    eliminarsocios = Bajasdesocios(None, -1, "")
    app.SetTopWindow(eliminarsocios)
    eliminarsocios.Show()
    app.MainLoop()
