#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Jun 28 14:17:32 2010

import wx
import sys
import MySQLdb
# begin wxGlade: extracode
# end wxGlade



class MyPelicula(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyPelicula.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        self.db = MySQLdb.connect('localhost', 'cintia', 'cintia', 'cintia', charset='UTF8')
        wx.Frame.__init__(self, *args, **kwds)
        self.list_pelicula = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyPelicula.__set_properties
        self.SetTitle("listadepeli")
        columnas = [u'Item a considerar', 'Pelicula','Genero','Duracion' ,'Protagonista','Director','Origen','Alquilada'] 
        for col, text in enumerate(columnas):
            self.list_pelicula.InsertColumn(col, text)
        self.list_pelicula.SetColumnWidth(0, 300)
        self.list_pelicula.SetColumnWidth(1,150)
        self.list_pelicula.SetColumnWidth(2,105)
        self.list_pelicula.SetColumnWidth(3, wx.LIST_AUTOSIZE_USEHEADER)
        self.list_pelicula.SetColumnWidth(4, wx.LIST_AUTOSIZE_USEHEADER)
        self.list_pelicula.SetColumnWidth(5, wx.LIST_AUTOSIZE_USEHEADER)
        self.list_pelicula.SetColumnWidth(6, wx.LIST_AUTOSIZE_USEHEADER)
        self.list_pelicula.SetColumnWidth(7, wx.LIST_AUTOSIZE_USEHEADER)
       
        c = self.db.cursor()
        c.execute('''SELECT* FROM Videoclub ''')
        q = c.fetchall()
        for lista in q:
            index = self.list_pelicula.InsertStringItem(sys.maxint, str(lista[0]))
            for colu, text in enumerate (lista[1:]):
                self.list_pelicula.SetStringItem(index, colu+1, str(text))
        c.close()

    def __do_layout(self):
        # begin wxGlade: MyPelicula.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.list_pelicula, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyPelicula


if __name__ == "__main__":
    ListadePelicula = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyPelicula(None, -1, "")
    ListadePelicula.SetTopWindow(frame_1)
    frame_1.Show()
    ListadePelicula.MainLoop()
