#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Jul 15 15:27:51 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame2.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_3_menubar = wx.MenuBar()
        self.alta = wx.Menu()
        self.altapelicula = wx.MenuItem(self.alta, wx.NewId(), "A&ltadepelicula", "", wx.ITEM_NORMAL)
        self.alta.AppendItem(self.altapelicula)
        self.altasocios = wx.MenuItem(self.alta, wx.NewId(), "A&lta de socios", "", wx.ITEM_NORMAL)
        self.alta.AppendItem(self.altasocios)
        self.altaalquiler = wx.MenuItem(self.alta, wx.NewId(), "A&lta alquiler", "", wx.ITEM_NORMAL)
        self.alta.AppendItem(self.altaalquiler)
        self.frame_3_menubar.Append(self.alta, "&Alta ")
        self.modificacion = wx.Menu()
        self.modificacionpeli = wx.MenuItem(self.modificacion, wx.NewId(), "M&odificacion de Pelicula", "", wx.ITEM_NORMAL)
        self.modificacion.AppendItem(self.modificacionpeli)
        self.modificacionsocios = wx.MenuItem(self.modificacion, wx.NewId(), "M&odificacion de Socios", "", wx.ITEM_NORMAL)
        self.modificacion.AppendItem(self.modificacionsocios)
        self.frame_3_menubar.Append(self.modificacion, "M&odificacion ")
        self.baja = wx.Menu()
        self.bajapelicula = wx.MenuItem(self.baja, wx.NewId(), "B&aja de Pelicula", "", wx.ITEM_NORMAL)
        self.baja.AppendItem(self.bajapelicula)
        self.bajasocios = wx.MenuItem(self.baja, wx.NewId(), "B&aja de Socios", "", wx.ITEM_NORMAL)
        self.baja.AppendItem(self.bajasocios)
        self.frame_3_menubar.Append(self.baja, "B&aja ")
        self.listado = wx.Menu()
        self.listapeli = wx.MenuItem(self.listado, wx.NewId(), "L&ista de Pelicula", "", wx.ITEM_NORMAL)
        self.listado.AppendItem(self.listapeli)
        self.listasocios = wx.MenuItem(self.listado, wx.NewId(), "L&ista de Socios", "", wx.ITEM_NORMAL)
        self.listado.AppendItem(self.listasocios)
        self.listaalquiler = wx.MenuItem(self.listado, wx.NewId(), "L&ista de Alquiler", "", wx.ITEM_NORMAL)
        self.listado.AppendItem(self.listaalquiler)
        self.frame_3_menubar.Append(self.listado, "L&istado")
        self.SetMenuBar(self.frame_3_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnAltapeli, self.altapelicula)
        self.Bind(wx.EVT_MENU, self.OnAltasocios, self.altasocios)
        self.Bind(wx.EVT_MENU, self.OnAlquiler, self.altaalquiler)
        self.Bind(wx.EVT_MENU, self.OnModpeli, self.modificacionpeli)
        self.Bind(wx.EVT_MENU, self.OnModsocios, self.modificacionsocios)
        self.Bind(wx.EVT_MENU, self.OnBajapeli, self.bajapelicula)
        self.Bind(wx.EVT_MENU, self.OnBajasocio, self.bajasocios)
        self.Bind(wx.EVT_MENU, self.OnListpeli, self.listapeli)
        self.Bind(wx.EVT_MENU, self.OnListsocios, self.listasocios)
        self.Bind(wx.EVT_MENU, self.OnListalquiler, self.listaalquiler)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame2.__set_properties
        self.SetTitle("videoclub")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame2.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

    def OnAltapeli(self, event): # wxGlade: MyFrame2.<event_handler>
        import  registropeli  
        ventana = registropeli.Pelicula(None, -1, u"Registro de Pelicula")
        ventana.CenterOnScreen()
        ventana.Show()
        return True
    def OnAltasocios(self, event): # wxGlade: MyFrame2.<event_handler>
        import  registropeli  
        ventana = registropeli.Pelicula(None, -1, u"Registro de Pelicula")
        ventana.CenterOnScreen()
        ventana.Show()
        return True
    def OnAlquiler(self, event): # wxGlade: MyFrame2.<event_handler>
        import  prestamos  
        ventana = prestamos.Prestamos(None, -1, u"Registro de Alquiler")
        ventana.CenterOnScreen()
        ventana.Show()
        return True

    def OnModpeli(self, event): # wxGlade: MyFrame2.<event_handler>
        import  modificarpely  
        ventana = modificarpely.Modificar(None, -1, u"Modificacion de Pelicula")
        ventana.CenterOnScreen()
        ventana.Show()
        return True

    def OnModsocios(self, event): # wxGlade: MyFrame2.<event_handler>
        import  modificarsocios 
        ventana = modificarsocios.Modificarsocio(None, -1, u"Modificacion de Socios")
        ventana.CenterOnScreen()
        ventana.Show()
        return True
    def OnBajapeli(self, event): # wxGlade: MyFrame2.<event_handler>
        import  Bajasdepely
        ventana = Bajasdepely.Bajasdepely(None, -1, u"Bajas de Pelicula")
        ventana.CenterOnScreen()
        ventana.Show()
        return True
    def OnBajasocio(self, event): # wxGlade: MyFrame2.<event_handler>
        import  bajadesocio
        ventana = bajadesocio.Bajasdesocios(None, -1, u"Bajas de Pelicula")
        ventana.CenterOnScreen()
        ventana.Show()
        return True

    def OnListpeli(self, event): # wxGlade: MyFrame2.<event_handler>
        import  listapeli
        ventana = listapeli.MyPelicula(None, -1, u"Lista de Pelicula")
        ventana.CenterOnScreen()
        ventana.Show()
        return True

    def OnListsocios(self, event): # wxGlade: MyFrame2.<event_handler>
        import  listasocios
        ventana = listasocios.MyLista(None, -1, u"Lista de Socios")
        ventana.CenterOnScreen()
        ventana.Show()
        return True

    def OnListalquiler(self, event): # wxGlade: MyFrame2.<event_handler>
        import  lista_alquiler
        ventana = lista_alquiler.MyAlquiler(None, -1, u"Lista de Alquiler")
        ventana.CenterOnScreen()
        ventana.Show()
        return True

# end of class MyFrame2


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_3 = MyFrame2(None, -1, "")
    app.SetTopWindow(frame_3)
    frame_3.Show()
    app.MainLoop()
